import React from 'react';
import VideoCard from './VideoCard';

const CommunityBlueprint = ({ vision }) => {
    if (!vision) return null;
    return (
        <div className="w-full max-w-4xl mx-auto py-12 px-6 animate-df-fade-in">
            <div className="bg-white border-[3px] border-devfolio-blue/10 rounded-[2.5rem] shadow-2xl shadow-devfolio-blue/5 overflow-hidden relative">
                {/* Decorative Header */}
                <div className="bg-gradient-to-r from-devfolio-blue to-cyan-500 p-8 text-white relative">
                    <div className="absolute top-0 right-0 p-8 opacity-10">
                        <svg width="120" height="120" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
                        </svg>
                    </div>
                    <p className="text-[10px] font-black uppercase tracking-[0.4em] mb-2 opacity-90">Personalized Atlas Insight</p>
                    <h1 className="text-4xl font-black tracking-tighter">Blue Ocean Niche Blueprint</h1>
                </div>

                <div className="p-10 space-y-12">
                    {/* Vision Section */}
                    <div>
                        <h3 className="text-devfolio-blue text-xs font-black uppercase tracking-widest mb-4 flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full bg-devfolio-blue"></span> The Strategic Vision
                        </h3>
                        <p className="text-2xl font-bold text-devfolio-text-primary leading-tight tracking-tight">
                            "{vision.vision}"
                        </p>
                    </div>

                    {/* Vibe Section */}
                    <div className="bg-cyan-50/50 rounded-3xl p-8 border border-cyan-100">
                        <h3 className="text-cyan-600 text-xs font-black uppercase tracking-widest mb-4 flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full bg-cyan-600"></span> Aesthetic & Vibe
                        </h3>
                        <p className="text-lg font-medium text-cyan-900 italic">
                            {vision.vibe}
                        </p>
                    </div>

                    {/* Roadmap Section */}
                    <div>
                        <h3 className="text-devfolio-green text-xs font-black uppercase tracking-widest mb-6 flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full bg-devfolio-green"></span> 90-Day Execution Roadmap
                        </h3>
                        <div className="space-y-4">
                            {vision.roadmap.map((step, i) => (
                                <div key={i} className="flex gap-4 items-start group">
                                    <div className="w-8 h-8 rounded-full bg-devfolio-green/10 flex items-center justify-center font-black text-devfolio-green text-xs shrink-0 group-hover:bg-devfolio-green group-hover:text-white transition-colors">
                                        {i + 1}
                                    </div>
                                    <p className="text-lg font-bold text-devfolio-text-secondary pt-0.5">
                                        {step}
                                    </p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                <div className="bg-devfolio-muted p-6 text-center border-t border-gray-100">
                    <p className="text-[9px] font-black text-devfolio-text-secondary uppercase tracking-[0.2em]">Generated by Bedrock Hyperbolic Engine</p>
                </div>
            </div>
        </div>
    );
};

const Feed = ({ videos, intent, onShowOnMap, communityVision = null }) => {
    if (communityVision) {
        return <CommunityBlueprint vision={communityVision} />;
    }

    if (!videos || videos.length === 0) return null;

    return (
        <div className="w-full max-w-6xl mx-auto animate-df-fade-in">
            {/* Intent Badge */}
            {intent && (
                <div className="mb-12 text-center bg-devfolio-muted border border-gray-100 p-10 rounded-3xl shadow-sm relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-1.5 bg-devfolio-blue"></div>
                    <h2 className="text-devfolio-blue text-[10px] uppercase tracking-[0.3em] font-black mb-4">Hyperbolic Vector Detected</h2>
                    <div className="text-5xl font-black text-devfolio-text-primary tracking-tighter mb-4">
                        {intent.sub_culture}
                    </div>
                    <div className="text-devfolio-text-secondary font-medium italic text-lg opacity-80 decoration-devfolio-green decoration-2 underline-offset-8 underline">
                        "{intent.vibe}"
                    </div>
                </div>
            )}

            {/* Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 overflow-y-auto max-h-[70vh] pr-2 custom-scrollbar">
                {videos.map(video => (
                    <VideoCard
                        key={video.video_id}
                        video={video}
                        onShowOnMap={onShowOnMap}
                    />
                ))}
            </div>
        </div>
    );
};

export default Feed;
